main: bz.ene.plugintest.Main
name: TestPlugin
version: '1.0'
description: A test plugin
author: Enebz
depend: [NBTAPI,]
commands:
  wishingwell:
    description: Foo command
    usage: /<command>